web_application/web_application/urls.py
from django.contrib import admin
from django.urls import path
from crud import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home),
    path('emp',views.emp),
    path('show',views.show),
    path('edit/<int:id>',views.edit),
    path('update/<int:id>',views.update),
    path('delete/<int:id>',views.delete),
]

web_application/crud/models.py
from django.db import models

class Employee(models.Model):
	eid = models.CharField(max_length=10)
	ename = models.CharField(max_length=50)
	eemail = models.EmailField()
	econtact = models.CharField(max_length=10)

	class Meta:
		db_table = "employee"

	def __str__(self):
		return self.ename

web_application/crud/forms.py
from django import forms
from crud.models import Employee

class EmployeeForm(forms.ModelForm):
	class Meta:
		model = Employee
		fields = "__all__"

web_application/crud/views.py
from django.shortcuts import render,redirect
from crud.forms import EmployeeForm
from crud.models import Employee

def emp(request):
	if request.method == "POST":
		form = EmployeeForm (request.POST) # here "form" is one varible
		if form.is_valid():
			try:
				form.save()
				return redirect("/show")
			except:
				pass
	else:
		form = EmployeeForm()
	return render(request,"index.html",{'form':form})

def show(request):
	employees = Employee.objects.all() # it's select query,select all data store in employees varible
	return render(request,"show.html",{'employees': employees})

def edit(request,id):
	employee = Employee.objects.get(id=id)
	return render(request,"edit.html",{'employee':employee})

def update(request,id):
	employee = Employee.objects.get(id=id)
	form = EmployeeForm(request.POST, instance=employee)
	if form.is_valid():
		form.save()
		return redirect('/show')
	return render(request,"edit.html",{'employee':employee})

def delete(request,id):
	employee = Employee.objects.get(id=id)
	employee.delete()
	return redirect("/show")

def home(request):
	return render(request,"home.html")

web_application/crud/templates/edit.html
<!DOCTYPE html>
<html>
<head>
	<title>Index</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
	<!-- <link rel="stylesheet" type="text/css" href="{% static '/style.css' %}"/> -->
</head>
<body>
<form method="POST" class="post-form" action="/update/{{employee.id}}">
		{% csrf_token %}

	<div class="container">
		<br>
		<div class="form-group row">
		<label class="col-sm-1 col-form-lable"></label>	
			<div class="col-sm-4">
				<h3>Update Details</h3>
			</div>
		</div>
	

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Employee ID : </label>
			<div class="col-sm-4">
				<input type="text" name="eid" id="id_eid" value="{{ employee.eid }}"/>
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Employee Name : </label>
			<div class="col-sm-4">
				<input type="text" name="ename" id="id_ename" value="{{ employee.ename }}"/>
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Employee Email : </label>
			<div class="col-sm-4">
				<input type="text" name="eemail" id="id_eemail" value="{{ employee.eemail }}"/>
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Employee Contact : </label>
			<div class="col-sm-4">
				<input type="text" name="econtact" id="id_econtact" value="{{ employee.econtact }}"/>
			</div>
		</div>
		<button type="submit" class="btn btn-success">Update</button>
	</div>

</form>
</body>
</html>

web_application/crud/templates/home.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
<!-- <nav>
	<ul>
		<li><a href="" class="btn btn-primary">Home</a></li>
		<li><a href="/emp" class="btn btn-primary">Add New Record</a></li>
		<li><a href="/show" class="btn btn-primary">Show</a></li>
	</ul>
</nav> -->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/emp">Add New Record</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/show">Show</span></a>
      </li>
    </ul>
    
  </div>
</nav>

web_application/crud/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Index</title>
	{% load staticfiles %}
	<!-- <link rel="stylesheet" type="text/css" href="{% static '/style.css' %}"/> -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>
<form method="POST" class="post-form" action="/emp">
		{% csrf_token %}

	<div class="container">
		<br>
		<div class="form-group row">
		<label class="col-sm-1 col-form-lable"></label>	
			<div class="col-sm-4">
				<h3>Enter Details</h3>
			</div>
		</div>
	

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Employee ID : </label>
			<div class="col-sm-4">
				{{ form.eid }}
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Employee Name : </label>
			<div class="col-sm-4">
				{{ form.ename }}
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Employee Email : </label>
			<div class="col-sm-4">
				{{ form.eemail }}
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-lable">Employee Contact : </label>
			<div class="col-sm-4">
				{{ form.econtact }}
			</div>
		</div>
		<button type="submit" class="btn btn-primary">Submit</button>
	</div>

</form>
</body>
</html>

web_application/crud/templates/show.html
<!DOCTYPE html>
<html>
<head>
	<title>Employee Record</title>
		{% load staticfiles %}
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
	<!-- <link rel="stylesheet" type="text/css" href="{% static '/style.css' %}"/> -->
</head>
<body>
	<div class="container">
	<table class="table table-striped table-bordered table-sm">
		<thead class="thead-dark">
			<tr>
				<th>Employee ID</th>
				<th>Employee Name</th>
				<th>Employee Email</th>
				<th>Employee Contact</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			{% for employee in employees %}
			<tr>
				<td>{{ employee.eid }}</td>
				<td>{{ employee.ename }}</td>
				<td>{{ employee.eemail }}</td>
				<td>{{ employee.econtact }}</td>
				<td>
					<a href="/edit/{{ employee.id}}"><span class="glyphicon glyphicon-pencil">Edit</span></a> | 
					<a href="/delete/{{ employee.id}}">Delete</a>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>
</div>
</body>
</html>